# Generated by Django 4.2.3 on 2023-08-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='book_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
